# Generated by Django 4.2.9 on 2026-04-24 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('lagos', 'Lagos'), ('port_harcourt', 'Port Harcourt'), ('abuja', 'Abuja')], max_length=20)),
                ('area_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('mixed', 'Mixed Use'), ('market', 'Market Area'), ('religious', 'Religious/Event Area')], default='mixed', max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Max number of cars')),
                ('price_per_hour', models.DecimalField(decimal_places=2, help_text='Price in Nigerian Naira (NGN)', max_digits=10)),
                ('price_is_negotiable', models.BooleanField(default=False)),
                ('available_from', models.TimeField(blank=True, help_text='e.g. 07:00', null=True)),
                ('available_until', models.TimeField(blank=True, help_text='e.g. 21:00', null=True)),
                ('available_days', models.JSONField(default=list, help_text='e.g. ["monday", "tuesday", "friday"]')),
                ('source', models.CharField(choices=[('admin', 'Admin Added'), ('user', 'User Submitted'), ('extracted', 'Extracted from Text')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by admin')),
                ('has_security', models.BooleanField(default=False)),
                ('is_covered', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Special instructions, restrictions, landmarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parking Space',
                'verbose_name_plural': 'Parking Spaces',
                'db_table': 'parking_spaces',
                'ordering': ['-created_at'],
            },
        ),
    ]
