# Generated by Django 4.2.9 on 2026-04-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('body', models.TextField()),
                ('state_before', models.CharField(blank=True, max_length=30)),
                ('state_after', models.CharField(blank=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'whatsapp_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('find_city', 'Finding: City'), ('find_area', 'Finding: Area Type'), ('find_time', 'Finding: Time'), ('find_budget', 'Finding: Budget'), ('find_result', 'Finding: Showed Results'), ('submit_start', 'Submit: Started'), ('submit_name', 'Submit: Collecting Name'), ('submit_city', 'Submit: Collecting City'), ('submit_addr', 'Submit: Collecting Address'), ('submit_price', 'Submit: Collecting Price'), ('submit_cap', 'Submit: Collecting Capacity'), ('submit_hours', 'Submit: Collecting Hours'), ('extract_wait', 'Extract: Waiting for Text')], default='idle', max_length=30)),
                ('data', models.JSONField(default=dict, help_text='Collected form data for current flow')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'whatsapp_sessions',
            },
        ),
    ]
