# Generated by Django 4.2.9 on 2026-04-24 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available ✅'), ('full', 'Full 🔴'), ('gone', 'Space No Longer Exists ❌'), ('unsafe', 'Feels Unsafe ⚠️')], max_length=20)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.parkingspace')),
            ],
            options={
                'db_table': 'availability_reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
